#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/buildroot-2012.08/arm920t/usr/bin/arm-linux-gcc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -O3 -Wall -DMD32_REG_T=int"
  #define PLATFORM "linux-x86_64"
  #define DATE "Mon May 29 14:06:05 CST 2017"
#endif
