#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/buildroot-2012.08/arm920t/usr/bin/arm-linux-gcc -O"
  #define PLATFORM "dist"
  #define DATE "Mon May 29 14:15:45 CST 2017"
#endif
